// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/TeleopDrive.h"

/**
 * @brief Construct a new Teleop Drive:: Teleop Drive object
 * 
 * Set the default drive move to arcade drive voltage (although velocity is mainly used).
 * Also make sure to get drivetrain for the driving!
 */
TeleopDrive::TeleopDrive(): frc::Command(), 
driveMode((DriveMode) frc::Preferences::GetInstance()->GetInt("Drive Mode", arcadeDriveVoltage))
 {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain.get());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

/**
 * @brief Called just before this Command runs the first time
 */
void TeleopDrive::Initialize() {
}

/**
 * @brief Called repeatedly when this Command is scheduled to run
 * 
 * Get x and y axes from both driver and operator joysticks.
 * Then feed them into the proper driveTrain functions depending on the current driveMode.
 */
void TeleopDrive::Execute()
{
        double xAxis = Robot::oi->getDriverJoystick()->GetRawAxis(4);
        double yAxis = Robot::oi->getDriverJoystick()->GetRawAxis(1);

        double speedPos = Robot::oi->getDriverJoystick()->GetRawAxis(3);
        double speedNeg = Robot::oi->getDriverJoystick()->GetRawAxis(2);

        double speedVoltage = 0.0;
        double speedVelocity = 0.0;

        switch (driveMode)
        {

        case DriveMode::arcadeDriveVelocity:
            if(speedNeg > 0.05){
                speedVelocity = -speedNeg;
            } else if(speedPos > 0.05){
                speedVelocity = speedPos;
            } else {
                speedVelocity = 0.0;
            }

            //Robot::driveTrain->VelocityArcade(speedVelocity, -xAxis);
            Robot::driveTrain->VelocityArcade(-yAxis, -speedVelocity);
            break;
        case DriveMode::arcadeDriveVoltage:
            if(speedNeg > 0.05){
                speedVoltage = -speedNeg;
            } else if(speedPos > 0.05){
                speedVoltage = speedPos;
            } else {
                speedVoltage = 0.0;
            }

            std::cout << speedVoltage << std::endl;
            std::cout << xAxis << std::endl;

            //Robot::driveTrain->ArcadeDrive(speedVoltage, -xAxis);
            Robot::driveTrain->VelocityArcade(-yAxis, -speedVoltage);
            break;
        default:
            break;
        }
    
}

/**
 * @brief Make this return true when this Command no longer needs to run execute()
 * 
 * @return false (by default)
 */
bool TeleopDrive::IsFinished() {
    return false;
}

/**
 * @brief Called once after isFinished returns true
 */
void TeleopDrive::End() {
    
}

/**
 * @brief Called when another command which requires one or more of the same subsystems is scheduled to run
 */
void TeleopDrive::Interrupted() {

}
